version: '3.8'

services:
  # Supabase Database
  supabase-db:
    image: postgres:15
    container_name: kidoers-test-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "54322:5432"
    volumes:
      - supabase_test_db_data:/var/lib/postgresql/data
      - ./docker/supabase/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Supabase Auth (GoTrue)
  supabase-auth:
    image: supabase/gotrue:v2.143.0
    container_name: kidoers-test-auth
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: http://localhost:54321
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:postgres@supabase-db:5432/postgres
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_URI_ALLOW_LIST: "*"
      GOTRUE_DISABLE_SIGNUP: false
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      GOTRUE_EXTERNAL_EMAIL_ENABLED: false
      GOTRUE_MAILER_AUTOCONFIRM: true
      GOTRUE_SMTP_ADMIN_EMAIL: admin@example.com
      GOTRUE_SMTP_HOST: supabase-inbucket
      GOTRUE_SMTP_PORT: 2500
      GOTRUE_SMTP_USER: fake_mail_user
      GOTRUE_SMTP_PASS: fake_mail_password
      GOTRUE_SMTP_SENDER_NAME: fake_sender
      GOTRUE_DISABLE_SIGNUP: false
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: /auth/confirm
      GOTRUE_MAILER_URLPATHS_RECOVERY: /auth/recover
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: /auth/email-change
    ports:
      - "54321:9999"
    depends_on:
      supabase-db:
        condition: service_healthy
      supabase-inbucket:
        condition: service_started

  # Supabase REST API (PostgREST)
  supabase-rest:
    image: postgrest/postgrest:v12.0.1
    container_name: kidoers-test-rest
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@supabase-db:5432/postgres
      PGRST_DB_SCHEMAS: public,storage,graphql_public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      PGRST_DB_USE_LEGACY_GUCS: "false"
      PGRST_APP_SETTINGS_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      PGRST_APP_SETTINGS_JWT_EXP: 3600
    ports:
      - "54320:3000"
    depends_on:
      supabase-db:
        condition: service_healthy

  # Supabase Studio
  supabase-studio:
    image: supabase/studio:20241015-0a8b8b8
    container_name: kidoers-test-studio
    environment:
      SUPABASE_URL: http://localhost:54321
      SUPABASE_REST_URL: http://localhost:54320/rest/v1/
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTk5OTk5OTksImV4cCI6MjAwMDAwMDAwMH0.example
      SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY5OTk5OTk5OSwiZXhwIjoyMDAwMDAwMDAwfQ.example
    ports:
      - "54323:3000"
    depends_on:
      - supabase-auth
      - supabase-rest

  # Supabase Inbucket (Email testing)
  supabase-inbucket:
    image: inbucket/inbucket:3.0.1
    container_name: kidoers-test-inbucket
    ports:
      - "54324:9000"
      - "54325:2500"

  # Kidoers Backend API
  kidoers-backend:
    build:
      context: ../kidoers_backend
      dockerfile: Dockerfile
    container_name: kidoers-test-backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@supabase-db:5432/postgres
      - SUPABASE_URL=http://supabase-auth:9999
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTk5OTk5OTksImV4cCI6MjAwMDAwMDAwMH0.example
      - SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY5OTk5OTk5OSwiZXhwIjoyMDAwMDAwMDAwfQ.example
    ports:
      - "8001:8000"
    depends_on:
      supabase-db:
        condition: service_healthy
      supabase-auth:
        condition: service_started
    volumes:
      - ../kidoers_backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  supabase_test_db_data: